content:
    resource: "@ContentBundle/Resources/config/routing.yml"
    prefix:   /

geo:
    resource: "@GeoBundle/Resources/config/routing.yml"
    prefix:   /

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /

edu_speak:
    resource: "@EduSpeakBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

users:
    type: rest
    prefix: /api
    resource: "@EduSpeakBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
