content:
    resource: "@ContentBundle/Resources/config/routing.yml"
    prefix:   /content

geo:
    resource: "@GeoBundle/Resources/config/routing.yml"
    prefix:   /geo

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /discussion

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

users:
    type: rest
    prefix: /api
    resource: "@EduSpeakBundle/Resources/config/routing.yml"

chat_rest:
    type:     rest
    prefix: /api
    resource: ChatBundle\Controller\ChatController

message_rest:
    type:     rest
    prefix: /api
    resource: ChatBundle\Controller\MessageController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

edu_speak:
    resource: "@EduSpeakBundle/Resources/config/routing.yml"
    prefix:   /
