services:
    sonata.admin.user:
        class: EduSpeakBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - EduSpeakBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [EduSpeakBundle]]