edu_speak_profil:
    path:     /user/{id}
    defaults: { _controller: EduSpeakBundle:Default:profil }

edu_speak_homepage:
    path:     /
    defaults: { _controller: EduSpeakBundle:Default:index }

edu_speek_User:
    type: rest
    prefix: /v1
    resource: "EduSpeakBundle\Controller\UserController"
