chat_homepage:
    path:     /
    defaults: { _controller: ChatBundle:Default:index }

chat_list:
    path:     /list
    defaults: { _controller: ChatBundle:Discussion:show }

chat_create:
    path:     /start/{id}
    defaults: { _controller: ChatBundle:Discussion:create }
